version: "3.9"

services:
  pg:
    container_name: pg
    image: postgis/postgis:14-3.2-alpine
    environment:
      POSTGRES_USER: nekoyashi
      POSTGRES_PASSWORD: 111111
      POSTGRES_DB: poker-history
    volumes:
      - poker-history:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    restart: always
    # environment:
    #   RABBITMQ_DEFAULT_USER: nekoyashi
    #   RABBITMQ_DEFAULT_PASS: 111111
    ports:
      - 15672:15672
      - 5672:5672
    # env_file:
    #   - ./rabbitmq.env

volumes: 
  poker-history:
  redis:
